CREATE DATABASE Television

GO

USE Television

CREATE TABLE Channel(
ChannelId INT PRIMARY KEY IDENTITY,
CurrentChannel INT NOT NULL,
DateCreated DATETIME NOT NULL DEFAULT(GETDATE())
)

CREATE TABLE Volume(
VolumeId INT PRIMARY KEY IDENTITY,
CurrentVolume INT NOT NULL,
DateCreated DATETIME NOT NULL DEFAULT(GETDATE())
)
CREATE TABLE Source(
SourceId INT PRIMARY KEY IDENTITY,
CurrentSource INT NOT NULL,
DateCreated DATETIME NOT NULL DEFAULT(GETDATE())
)
CREATE TABLE Settings(
SettingsId INT PRIMARY KEY IDENTITY,
SettingsChannel INT NOT NULL,
SettingsVolume INT NOT NULL,
DateCreated DATETIME NOT NULL DEFAULT(GETDATE())
)
